import type { Scheme } from '../types';

export const schemeData: Scheme[] = [
  {
    id: 'pm-kisan',
    name: 'PM Kisan Samman Nidhi',
    description: 'Income support of ₹6,000 per year to small and marginal farmer families with landholding up to 2 hectares.',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
    scope: 'central',
    eligibility: { maxAnnualIncome: 200000, states: [], categories: [], occupation: 'farmer' },
    benefits: '₹6,000 per year in three equal instalments of ₹2,000 each, directly credited to bank account.',
    documents: ['Aadhaar Card', 'Land Records', 'Bank Account Details'],
    howToApply: 'Visit PM Kisan portal (pmkisan.gov.in) or nearest Common Service Centre. The scheme is also integrated with state land records for automatic enrolment.',
    officialLink: 'https://pmkisan.gov.in',
    icon: '🌾',
    active: true,
    tags: ['farmer', 'income-support', 'central'],
  },
  {
    id: 'ayushman-bharat',
    name: 'Ayushman Bharat - PM Jan Arogya Yojana',
    description: 'Health coverage of ₹5 lakh per family per year for secondary and tertiary care hospitalization.',
    ministry: 'Ministry of Health & Family Welfare',
    scope: 'central',
    eligibility: { states: [], categories: ['sc', 'st', 'obc', 'ews'], maxAnnualIncome: 250000 },
    benefits: 'Cashless healthcare coverage up to ₹5 lakh per family per year. Covers pre-existing diseases from day one.',
    documents: ['Aadhaar Card', 'BPL Certificate', 'Ration Card'],
    howToApply: 'Visit nearest empanelled hospital or Common Service Centre. Eligible families are identified through SECC database.',
    officialLink: 'https://pmjay.gov.in',
    icon: '🏥',
    active: true,
    tags: ['health', 'insurance', 'bpl', 'central'],
  },
  {
    id: 'nsp',
    name: 'National Scholarship Portal (NSP)',
    description: 'Central sector scholarships for SC, ST, OBC, and minority community students pursuing higher education.',
    ministry: 'Ministry of Education',
    scope: 'central',
    eligibility: { minAge: 16, maxAge: 35, states: [], categories: ['sc', 'st', 'obc'], maxAnnualIncome: 250000, occupation: 'student' },
    benefits: 'Tuition fee reimbursement up to ₹30,000 per year and maintenance allowance of ₹10,000 per year for 10 months.',
    documents: ['Aadhaar Card', 'Income Certificate', 'Caste Certificate', 'Previous Academic Marksheet', 'Bank Account Details'],
    howToApply: 'Apply online through National Scholarship Portal (scholarships.gov.in) during the application window (August-November).',
    officialLink: 'https://scholarships.gov.in',
    icon: '📚',
    active: true,
    tags: ['education', 'scholarship', 'student', 'central'],
  },
  {
    id: 'pm-awas',
    name: 'Pradhan Mantri Awas Yojana (Urban)',
    description: 'Housing for All — affordable housing with interest subsidy for EWS/LIG/MIG categories.',
    ministry: 'Ministry of Housing & Urban Affairs',
    scope: 'central',
    eligibility: { maxAnnualIncome: 1800000, categories: ['ews'] },
    benefits: 'Interest subsidy of 3-6.5% on home loans up to ₹12 lakh. Credit-linked subsidy scheme for affordable housing.',
    documents: ['Aadhaar Card', 'Income Certificate', 'Address Proof'],
    howToApply: 'Apply through PMAY portal (pmay-urban.gov.in) or visit nearest Municipal Corporation office.',
    officialLink: 'https://pmay-urban.gov.in',
    icon: '🏠',
    active: true,
    tags: ['housing', 'subsidy', 'urban', 'central'],
  },
  {
    id: 'ujjwala',
    name: 'Ujjwala Yojana (PMUY)',
    description: 'Free LPG connections to women from BPL households to promote clean cooking fuel.',
    ministry: 'Ministry of Petroleum & Natural Gas',
    scope: 'central',
    eligibility: { maxAnnualIncome: 120000, gender: 'female', categories: ['sc', 'st', 'obc'] },
    benefits: 'Free LPG connection with first refill and stove provided to eligible BPL households.',
    documents: ['Aadhaar Card', 'BPL Certificate', 'Ration Card'],
    howToApply: 'Apply through nearest LPG distributor or Common Service Centre with BPL certificate.',
    officialLink: 'https://pmuy.gov.in',
    icon: '🔥',
    active: true,
    tags: ['women', 'lpg', 'bpl', 'central'],
  },
  {
    id: 'ssp',
    name: 'State Scholarship Portal (Various States)',
    description: 'State-specific scholarships for students belonging to SC/ST/OBC and minority communities.',
    ministry: 'State Education Department',
    scope: 'state',
    eligibility: { minAge: 15, maxAge: 30, categories: ['sc', 'st', 'obc', 'ews'], maxAnnualIncome: 150000, occupation: 'student' },
    benefits: 'Full tuition fee waiver for government colleges and maintenance allowance of ₹5,000-₹12,000 per year depending on state.',
    documents: ['Aadhaar Card', 'Income Certificate', 'Caste Certificate', 'Domicile Certificate'],
    howToApply: 'Apply through respective State e-Scholarship portal. Deadlines vary by state — usually August to October.',
    officialLink: 'https://scholarships.gov.in',
    icon: '🎓',
    active: true,
    tags: ['education', 'state-scholarship', 'student'],
  },
  {
    id: 'pm-mudra',
    name: 'PM Mudra Yojana',
    description: 'Loans up to ₹10 lakh for non-corporate, non-farm small/micro enterprises.',
    ministry: 'Ministry of Finance',
    scope: 'central',
    eligibility: { minAge: 18, maxAge: 65, maxAnnualIncome: 500000, occupation: 'self-employed' },
    benefits: 'Collateral-free loans up to ₹10 lakh under three categories: Shishu (up to ₹50k), Kishor (₹50k-₹5L), Tarun (₹5L-₹10L).',
    documents: ['Aadhaar Card', 'PAN Card', 'Business Proof', 'Bank Statement'],
    howToApply: 'Apply at any scheduled commercial bank, regional rural bank, or micro-finance institution. Also available online through Udyam portal.',
    officialLink: 'https://www.mudra.org.in',
    icon: '💼',
    active: true,
    tags: ['loan', 'business', 'entrepreneur', 'central'],
  },
  {
    id: 'pm-svanidhi',
    name: 'PM SVANidhi Scheme',
    description: 'Working capital loans up to ₹10,000 for street vendors to restart their businesses post-COVID.',
    ministry: 'Ministry of Housing & Urban Affairs',
    scope: 'central',
    eligibility: { minAge: 18, maxAge: 60, maxAnnualIncome: 150000, occupation: 'vendor' },
    benefits: 'Initial loan of ₹10,000, then ₹20,000, then ₹50,000 with 7% interest subsidy on timely repayment. Digital transaction bonus of ₹100/month.',
    documents: ['Aadhaar Card', 'Vendor ID Certificate', 'Bank Account'],
    howToApply: 'Apply through nearest Municipal Corporation office or urban local body. Also available via PM SVANidhi portal.',
    officialLink: 'https://pmsvanidhi.mohua.gov.in',
    icon: '🛒',
    active: true,
    tags: ['loan', 'vendor', 'micro-business', 'central'],
  },
  {
    id: 'standup-india',
    name: 'Stand-Up India Scheme',
    description: 'Bank loans between ₹10 lakh and ₹1 crore for SC/ST and women entrepreneurs.',
    ministry: 'Ministry of Finance',
    scope: 'central',
    eligibility: { minAge: 18, maxAge: 70, categories: ['sc', 'st'], maxAnnualIncome: 1000000, occupation: 'entrepreneur' },
    benefits: 'Composite loan of ₹10 lakh to ₹1 crore including working capital. 15% margin money allowed. Repayment up to 7 years.',
    documents: ['Aadhaar Card', 'Caste Certificate', 'Project Report', 'Business Plan'],
    howToApply: 'Apply at any scheduled commercial bank branch. At least one SC/ST and one woman entrepreneur per bank branch are supported.',
    officialLink: 'https://www.standupmitra.in',
    icon: '🚀',
    active: true,
    tags: ['loan', 'entrepreneur', 'scst', 'women', 'central'],
  },
  {
    id: 'rte',
    name: 'Right to Education (RTE) Act - 25% Quota',
    description: 'Free and compulsory education for children aged 6-14 with 25% reservation for disadvantaged groups in private schools.',
    ministry: 'Ministry of Education',
    scope: 'central',
    eligibility: { minAge: 6, maxAge: 14, categories: ['sc', 'st', 'obc', 'ews'], maxAnnualIncome: 100000 },
    benefits: 'Free education up to Class 8 in private schools. Reimbursement of fees to schools up to ₹50,000 per child per year.',
    documents: ['Birth Certificate', 'Income Certificate', 'Caste Certificate (if applicable)', 'BPL Certificate'],
    howToApply: 'Apply online through state RTE portals. Admission window is usually March-April each year.',
    officialLink: 'https://rte.mhrd.gov.in',
    icon: '📖',
    active: true,
    tags: ['education', 'child', 'bpl', 'central'],
  },
  {
    id: 'nrega',
    name: 'MGNREGA (Employment Guarantee)',
    description: '100 days of guaranteed wage employment per year to rural households whose adult members volunteer for unskilled work.',
    ministry: 'Ministry of Rural Development',
    scope: 'central',
    eligibility: { minAge: 18, maxAge: 60, occupation: 'rural-worker' },
    benefits: '100 days of employment per rural household. Minimum wage as per state rates (₹200-₹300 per day). Equal wages for men and women.',
    documents: ['Aadhaar Card', 'Ration Card', 'Bank Account', 'Job Card'],
    howToApply: 'Apply at Gram Panchayat office for Job Card. Once registered, you can demand work through written application or phone.',
    officialLink: 'https://nrega.nic.in',
    icon: '🔨',
    active: true,
    tags: ['employment', 'rural', 'wage', 'central'],
  },
  {
    id: 'igmaps',
    name: 'Indira Gandhi National Old Age Pension (IGNOAPS)',
    description: 'Monthly pension for senior citizens aged 60 years and above belonging to BPL families.',
    ministry: 'Ministry of Rural Development',
    scope: 'central',
    eligibility: { minAge: 60, maxAnnualIncome: 50000, categories: ['sc', 'st', 'obc', 'ews'] },
    benefits: '₹200 per month for ages 60-79, ₹500 per month for ages 80 and above. Some states add top-up amounts.',
    documents: ['Aadhaar Card', 'Age Proof', 'BPL Certificate', 'Bank Account'],
    howToApply: 'Apply at nearest Common Service Centre or state Social Welfare Department office.',
    officialLink: 'https://nsap.nic.in',
    icon: '👴',
    active: true,
    tags: ['pension', 'senior-citizen', 'bpl', 'central'],
  },
  {
    id: 'pmjjm',
    name: 'PM Jan Dhan Yojana',
    description: 'Universal access to banking facilities with at least one basic banking account for every household.',
    ministry: 'Ministry of Finance',
    scope: 'central',
    eligibility: { minAge: 10, states: [], categories: [] },
    benefits: 'Zero-balance savings account, RuPay debit card, ₹1 lakh accident insurance, overdraft facility up to ₹10,000.',
    documents: ['Aadhaar Card', 'Proof of Address', 'Passport-size Photo'],
    howToApply: 'Visit any bank branch with Aadhaar card. Accounts can also be opened through Business Correspondents visiting villages.',
    officialLink: 'https://pmjdy.gov.in',
    icon: '🏦',
    active: true,
    tags: ['banking', 'universal', 'financial-inclusion', 'central'],
  },
  {
    id: 'pm-kaushal',
    name: 'PM Kaushal Vikas Yojana',
    description: 'Free skill training and certification for youth to enhance employability.',
    ministry: 'Ministry of Skill Development & Entrepreneurship',
    scope: 'central',
    eligibility: { minAge: 15, maxAge: 45, states: [], categories: [] },
    benefits: 'Free vocational training in 150+ job roles. Training allowance of ₹500-₹1,000 per day. Placement assistance provided.',
    documents: ['Aadhaar Card', 'Educational Certificate', 'Bank Account'],
    howToApply: 'Register on Skill India portal (skillindia.gov.in) or visit nearest PMKVY training centre.',
    officialLink: 'https://pmkvyofficial.org',
    icon: '🛠️',
    active: true,
    tags: ['skill', 'training', 'employment', 'youth', 'central'],
  },
  {
    id: 'fssai',
    name: 'Food Security Allowance (State PDS)',
    description: 'Subsidized food grains at ₹1-3 per kg to eligible households through Public Distribution System.',
    ministry: 'State Food & Civil Supplies Department',
    scope: 'state',
    eligibility: { states: [], categories: ['sc', 'st', 'obc', 'ews'], maxAnnualIncome: 150000 },
    benefits: 'Wheat at ₹2/kg, Rice at ₹3/kg, and coarse grains at ₹1/kg. 5 kg per person per month for priority households.',
    documents: ['Ration Card', 'Aadhaar Card', 'Income Certificate'],
    howToApply: 'Apply at nearest Food & Civil Supplies office. Names are added through the state food security portal.',
    officialLink: 'https://www.nfsa.gov.in',
    icon: '🍚',
    active: true,
    tags: ['food', 'pds', 'subsidy', 'state'],
  },
  {
    id: 'cheque',
    name: 'State Financial Assistance for Higher Education',
    description: 'Merit-cum-means financial assistance for pursuing professional/technical courses.',
    ministry: 'State Higher Education Department',
    scope: 'state',
    eligibility: { minAge: 17, maxAge: 30, categories: ['sc', 'st', 'obc', 'ews'], maxAnnualIncome: 250000, occupation: 'student' },
    benefits: 'Full tuition fee payment for government colleges. Interest-free education loans up to ₹5 lakh for professional courses.',
    documents: ['Aadhaar Card', 'Income Certificate', 'Caste Certificate', 'Previous Marksheet', 'College Admission Letter'],
    howToApply: 'Apply through state e-scholarship portal or Directorate of Higher Education office.',
    officialLink: 'https://scholarships.gov.in',
    icon: '🎯',
    active: true,
    tags: ['education', 'financial-assistance', 'higher-education', 'state'],
  },
  {
    id: 'pm-vishwakarma',
    name: 'PM Vishwakarma Yojana',
    description: 'Skill training and credit support for traditional artisans and craftspeople.',
    ministry: 'Ministry of Micro, Small & Medium Enterprises',
    scope: 'central',
    eligibility: { minAge: 18, maxAge: 60, maxAnnualIncome: 300000, occupation: 'artisan' },
    benefits: 'Skill training (5-7 days with ₹500/day stipend), toolkit incentive, collateral-free loan up to ₹3 lakh at 5% interest.',
    documents: ['Aadhaar Card', 'Identity Proof', 'Bank Account'],
    howToApply: 'Register on PM Vishwakarma portal or visit nearest Common Service Centre. Verification by local panchayat/municipality.',
    officialLink: 'https://pmvishwakarma.gov.in',
    icon: '🔧',
    active: true,
    tags: ['artisan', 'skill', 'loan', 'central'],
  },
  {
    id: 'pm-sym',
    name: 'PM Shri Yojana (PM Schools for Rising India)',
    description: 'Development of 14,500+ schools as model schools with modern infrastructure and pedagogy.',
    ministry: 'Ministry of Education',
    scope: 'central',
    eligibility: { minAge: 5, maxAge: 18, states: [], categories: [] },
    benefits: 'Access to modern school infrastructure, smart classrooms, labs, vocational training, and holistic education in PM Shri schools.',
    documents: ['Birth Certificate', 'Aadhaar Card', 'Previous School Records'],
    howToApply: 'Admission through respective PM Shri school. List of selected schools available on pmmsy.education.gov.in.',
    officialLink: 'https://pmmsy.education.gov.in',
    icon: '🏫',
    active: true,
    tags: ['education', 'school', 'infrastructure', 'central'],
  },
  {
    id: 'mbk',
    name: 'Mission Bhartiyam Kaushal (State Skill Mission)',
    description: 'State-level skill development program aligned with local industry needs.',
    ministry: 'State Skill Development Department',
    scope: 'state',
    eligibility: { minAge: 18, maxAge: 40, states: [], categories: [] },
    benefits: 'Free skill training in trades relevant to state economy. Monthly stipend of ₹1,000-₹2,000 during training. Job placement support.',
    documents: ['Aadhaar Card', 'Educational Certificate', 'Domicile Certificate'],
    howToApply: 'Register at state skill mission portal or visit nearest district skill development centre.',
    officialLink: 'https://skillindia.gov.in',
    icon: '⚙️',
    active: true,
    tags: ['skill', 'employment', 'training', 'state'],
  },
  {
    id: 'pm-surya',
    name: 'PM Suryodaya Yojana',
    description: 'Free solar panel installation for BPL households to reduce electricity costs.',
    ministry: 'Ministry of New & Renewable Energy',
    scope: 'central',
    eligibility: { categories: ['ews'], maxAnnualIncome: 100000 },
    benefits: 'Free rooftop solar panel installation (1-3 kW). 40% subsidy on panel cost for general households, 60% for BPL. Net metering allows selling excess power.',
    documents: ['Aadhaar Card', 'BPL Certificate', 'Electricity Bill', 'Rooftop Ownership Proof'],
    howToApply: 'Apply through DISCOM (power distribution company) office or state renewable energy development agency portal.',
    officialLink: 'https://mnre.gov.in',
    icon: '☀️',
    active: true,
    tags: ['solar', 'energy', 'subsidy', 'bpl', 'central'],
  },
];

export default schemeData;
